apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: devops-test-app:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ENV_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ENV_NAME
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ENV_NAME: "local"
